// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyq8MS61FHMQb41AjMySNUvUJEWXZpRP8',
    appId: '1:706006074978:web:27388510d88de6efc9333b',
    messagingSenderId: '706006074978',
    projectId: 'tt2-database',
    authDomain: 'tt2-database.firebaseapp.com',
    storageBucket: 'tt2-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_rwVI5LYur0s9dQlXCMK2NDsLos9w640',
    appId: '1:706006074978:android:de525067d686f68cc9333b',
    messagingSenderId: '706006074978',
    projectId: 'tt2-database',
    storageBucket: 'tt2-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuyjyJ7TaWsY_nPOal19lPLQBMwHhlsUg',
    appId: '1:706006074978:ios:a2652d701abe5c8bc9333b',
    messagingSenderId: '706006074978',
    projectId: 'tt2-database',
    storageBucket: 'tt2-database.appspot.com',
    iosClientId: '706006074978-ico69h7l47uagmm19qpgi4agc9sh32s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tt2',
  );
}
